language: go

services:
  - docker

script:
  - docker run --rm -i \
    -v $(pwd):/src \
    -v $(pwd)/public:/target \
    klakegg/hugo:0.69.0

deploy:
  local_dir: public # Default static site output dir for Hugo
  repo: wych42/wych42.github.io # This is the slug of the repo you want to deploy your site to
  target_branch: master # GitHub pages branch to deploy to (in other cases it can be gh-pages)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # This is the authentication which you will setup in the next step in travis-ci dashboard
  email: wych101010@gmail.com
  name: wych42
  on:
    branch: source
  fqdn: yuchi.me 
