baseURL = "https://yuchi.me/"
languageCode = "zh-cn"
title = "Chi's Journal"
theme = "hugo-octopress"
pygmentsCodeFences = true
disqusShortname = "chis-journal"

[params]
  subtitle = "Make it Bigger!"
  author = "chi"
  searchEngineURL = "https://www.google.com/search"
  rss = true
  sidebarHeader = ""
  sidebarText = """>> 已过的世代，无人记念；将来的世代，后来的人也不纪念。 - Ecclesiastes 1.11"""

[blackfriday]
  hrefTargetBlank = true
  angledQuotes = true
  fractions = true
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -10

[[menu.main]]
  name = "Archive"
  url = "/archive"
  weight = -9

[[menu.main]]
  name = "FinVerse"
  url = "/verse"
  weight = 1
