baseURL = "http://yuchi.me/"
title = "Chi's Journal"
theme = "calico-zen"
hasCJKLanguage = true
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
disqusShortname = "chis-journal"
paginate = 5

[languages]
  [languages.zh-CN]
    weight = 2
    languageName = "简体中文"
    contentDir = "content/cn"
  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content/en"

[params]
  subtitle = "- Ecclesiastes 1.11"
  mainSections = ["post"]
  favicon = "static/img/favicon.ico"
  dateFormat = "2006/01/02"
  googleAnalytics = "UA-164155675-1"
  truncateSummary = false
  selfHosted = true
  poweredBy = 'Written with <a target="_blank" href="https://www.gnu.org/software/emacs/">Emacs</a> and <a target="_blank" href="https://orgmode.org/">Org-mode</a>. Rendered by <a target="_blank" href="https://gohugo.io">Hugo</a> and <a target="_blank" href="https://github.com/wych42/calico-zen/">calico-zen</a>.'

[Author]
  name = "chi"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

[blackfriday]
  hrefTargetBlank = true
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    pre = "<i class='icon-home'></i>"
    weight = "-99"
  
  [[menu.main]]
    name = "Archive"
    url = "/archive"
    pre = "<i class='icon-folder-open-alt'></i>"
    weight = "-20"

   [[menu.main]]
    name = "Verse"
    url = "/verse"
    pre = "<i class='icon-paste'></i>"
    weight = "-10"

   [[menu.main]]
    name = "Tags"
    url = "/tags"
    pre = "<i class='icon-tags'></i>"
    weight = "-10"

  [[menu.main]]
    name = "Rss"
    url = "/index.xml"
    pre = "<i class='icon-rss'></i>"
    weight = "0"
 
