baseURL = "https://wych.blog/"
languageCode = "zh-cn"
title = "W's Journal"
theme = "beautifulhugo"

[params]
  subtitle = "Prepare your minds."
  author = "W"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[[menu.main]]
  name = "Blog"
  url = ""
  weight = 1

