baseURL = "https://yuchi.me/"
footnoteReturnLinkContents = "↩"
title = "Chi's Journal"
theme = "beautifulhugo"
hasCJKLanguage = true
languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
enableGitInfo = true
googleAnalytics = "UA-164155675-1"
disqusShortname = "chis-journal"

[languages]
  [languages.zh-CN]
    weight = 2
    languageName = "简体中文"
    contentDir = "content/cn"
  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content/en"

[params]
  subtitle = "- Ecclesiastes 1.11"
  mainSections = ["post"]
  favicon = "static/img/favicon.ico"
  dateFormat = "2006/01/02"
  hideAuthor = false
  gcse = "008088471589664132648:odwqgugznkt"
  commit = "https://github.com/wych42/wych42.github.io/"

[Author]
  name = "chi"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

[blackfriday]
  hrefTargetBlank = true
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -10

[[menu.main]]
  name = "Verse"
  url = "/verse"
  weight = -9
