baseURL = "https://yuchi.me/"
languageCode = "zh-cn"
title = "Chi's Journal"
theme = "hugo-octopress"
pygmentsCodeFences = true
disqusShortname = "chis-journal"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

[params]
  subtitle = "- Ecclesiastes 1.11"
  author = "chi"
  searchEngineURL = "https://www.google.com/search"
  rss = true
  mainSections = ["post"]
  pygmentscodefences = true
  pygmentsStyle = "solarized-dark"


[blackfriday]
  hrefTargetBlank = true
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -10

[[menu.main]]
  name = "Verse"
  url = "/verse"
  weight = -9

[[menu.main]]
  name = "Archive"
  url = "/archive"
  weight = 1

