baseURL = "https://yuchi.me/"
title = "Chi's Journal"
theme = "diary"
enableEmoji = true

hasCJKLanguage = true
languageCode = "zh"
defaultContentLanguage = "zh"

googleAnalytics = "UA-164155675-1"
paginate = 10

enableGitInfo = true

# PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
# # PygmentsUseClasses = true # Use CSS classes to format highlighted code
# PygmentsCodefencesGuessSyntax = true
# PygmentsOptions = "linenos=table"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "perldoc"
    tabWidth = 4

[languages]
  [languages.zh]
    weight = 2
    languageName = "简体中文"
    contentDir = "content/cn"
  # [[languages.zh.menu.main]]
  #   name = "笔记"
  #   url = "/verse/"
  #   weight = "-20"

  [[languages.zh.menu.main]]
    name = "归档"
    url = "/post/"
    weight = "-20"

  [[languages.zh.menu.main]]
    name = "标签"
    url = "/tags/"
    weight = "-10"

  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content/en"
  [[languages.en.menu.main]]
    name = "Notes"
    url = "/en/verse"
    weight = "-20"

  [[languages.en.menu.main]]
    name = "Archive"
    url = "/en/post"
    weight = "-20"

  [[languages.en.menu.main]]
    name = "Tags"
    url = "/en/tags"
    weight = "-10"

[params]
  since = "2018"
  homeFullContent = false
  rssFullContent = true   
  mainSections = ["post"]

  subtitle = "- Ecclesiastes 1.11"

  dateFormatToUse = "2006/01/02"
  showMenuLanguageChooser = true
  toc = true              
  photoswipe = true         

  favicon = "/favicon.png"
  truncateSummary = false
  poweredBy = 'Written with <a target="_blank" rel="noreferrer noopener" href="https://www.gnu.org/software/emacs/">Emacs</a> and <a target="_blank" rel="noreferrer noopener" href="https://orgmode.org/">Org-mode</a>. <br> Rendered by <a target="_blank" rel="noreferrer noopener" href="https://gohugo.io">Hugo</a>.<br> Theme <a target="_blank" rel="noreferrer noopener" href="https://github.com/amazingrise/hugo-theme-diary">Diary</a>(Modified).<br>Converted by <a target="_blank" rel="noreferrer noopener" href="https://ox-hugo.scripter.co/">ox-hugo</a>.'
  linksTwitter = "https://twitter.com/wych42"


  disqusShortname = "chis-journal"

[author]
  name = "chi"
