baseURL = "https://yuchi.me/"
title = "Chi's Journal"
theme = "jane"
enableEmoji = true

hasCJKLanguage = true
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"

googleAnalytics = "UA-164155675-1"
disqusShortname = "chis-journal"
paginate = 5

enableGitInfo = true

PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
PygmentsUseClasses = true # Use CSS classes to format highlighted code
PygmentsCodefencesGuessSyntax = true
PygmentsOptions = "linenos=table"

[languages]
  [languages.zh-CN]
    weight = 2
    languageName = "简体中文"
    contentDir = "content/cn"
  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content/en"

[params]
  since = "2018"
  homeFullContent = false
  rssFullContent = true   
  mainSections = ["post"]

  description = "- Ecclesiastes 1.11"

  archive-paginate = 20
  dateFormatToUse = "2006/01/02"
  showMenuLanguageChooser = true
  toc = true              
  photoswipe = true         

  favicon = "static/img/favicon.ico"
  truncateSummary = false
  selfHosted = true
  poweredBy = 'Written with <a target="_blank" href="https://www.gnu.org/software/emacs/">Emacs</a> and <a target="_blank" href="https://orgmode.org/">Org-mode</a>. Rendered by <a target="_blank" href="https://gohugo.io">Hugo</a> and <a target="_blank" href="https://github.com/wych42/calico-zen/">calico-zen</a>.'

[author]
  name = "chi"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    pre = "<i class='icon-home'></i>"
    weight = "-99"
  
  [[menu.main]]
    name = "Verse"
    url = "/verse/"
    pre = "<i class='icon-folder-open-alt'></i>"
    weight = "-20"

  [[menu.main]]
    name = "Archive"
    url = "/post/"
    pre = "<i class='icon-folder-open-alt'></i>"
    weight = "-20"

   [[menu.main]]
    name = "Tags"
    url = "/tags"
    pre = "<i class='icon-tags'></i>"
    weight = "-10"

  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    pre = "<i class='icon-rss'></i>"
    weight = "0"
 
