baseURL = "https://wych.blog/"
languageCode = "zh-cn"
title = "W's Journal"
theme = "hugo-octopress"

[params]
  subtitle = "Make it Bigger!"
  author = "W"
  searchEngineURL = "https://www.google.com/search"
  rss = true
  sidebarHeader = "Intro"
  sidebarText = "一点微小的人生经验。"

[blackfriday]
  hrefTargetBlank = true
  angledQuotes = true
  fractions = true
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -10

[[menu.main]]
  name = "FinWeekly"
  url = "/issue"
  weight = 1
