baseURL = "https://yuchi.me/"
title = "Chi's Journal"
theme = "jane"
enableEmoji = true

hasCJKLanguage = true
languageCode = "zh"
defaultContentLanguage = "zh"

googleAnalytics = "UA-164155675-1"
disqusShortname = "chis-journal"
paginate = 10

enableGitInfo = true

# PygmentsCodeFences = true # Enable syntax highlighting with GitHub flavoured code fences
# # PygmentsUseClasses = true # Use CSS classes to format highlighted code
# PygmentsCodefencesGuessSyntax = true
# PygmentsOptions = "linenos=table"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "perldoc"
    tabWidth = 4

[languages]
  [languages.zh]
    weight = 2
    languageName = "简体中文"
    contentDir = "content/cn"
  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content/en"

[params]
  since = "2018"
  homeFullContent = false
  rssFullContent = true   
  mainSections = ["post"]

  subtitle = "- Ecclesiastes 1.11"

  archive-paginate = 20
  dateFormatToUse = "2006/01/02"
  showMenuLanguageChooser = true
  toc = true              
  photoswipe = true         

  favicon = "/static/img/favicon.ico"
  truncateSummary = false
  poweredBy = 'Written with <a target="_blank" href="https://www.gnu.org/software/emacs/">Emacs</a> and <a target="_blank" href="https://orgmode.org/">Org-mode</a>. <br> Rendered by <a target="_blank" href="https://gohugo.io">Hugo</a> and <a href="https://github.com/amazingrise/hugo-theme-diary">Diary</a>.<br>Converted by <a target="_blank" href="https://ox-hugo.scripter.co/">ox-hugo</a>.'
  linksTwitter = "https://twitter.com/wych42"


[author]
  name = "chi"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    pre = "<i class='icon-home'></i>"
    weight = "-99"
  
  [[menu.main]]
    name = "Verse"
    url = "/verse/"
    pre = "<i class='icon-folder-open-alt'></i>"
    weight = "-20"

  [[menu.main]]
    name = "Archive"
    url = "/post/"
    pre = "<i class='icon-folder-open-alt'></i>"
    weight = "-20"

   [[menu.main]]
    name = "Tags"
    url = "/tags"
    pre = "<i class='icon-tags'></i>"
    weight = "-10"

  [[menu.main]]
    name = "RSS"
    url = "/index.xml"
    pre = "<i class='icon-rss'></i>"
    weight = "0"
 
