baseURL = "https://yuchi.me/"
languageCode = "en"
footnoteReturnLinkContents = "↩"
title = "Chi's Journal"
theme = "beautifulhugo"
hasCJKLanguage = true


DefaultContentLanguage = "en"
[languages]
  [languages.zh-CN]
    weight = 2
    contentDir = "content/cn"
  [languages.en]
    weight = 1
    contentDir = "content/en"

[params]
  subtitle = "- Ecclesiastes 1.11"
  mainSections = ["post"]
  favicon = "static/img/favicon.ico"
  dateFormat = "2006/01/02"
  hideAuthor = false
  googleAnalytics = "UA-164155675-1"
  disqusShortname = "chis-journal"
  gcse = "008088471589664132648:odwqgugznkt"

[Author]
  name = "chi"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark"
    tabWidth = 4

[blackfriday]
  hrefTargetBlank = true
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -10

[[menu.main]]
  name = "Verse"
  url = "/verse"
  weight = -9